import { AppProps } from 'next/app';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { SWRConfig } from 'swr';
import '../../styles/globals.css';
import store from '../redux/store';
import SideBar from '../components/SideBar';
import NavBar from '../components/NavBar';
import { fetcher } from '../utils/fetchHelpers';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <div className="flex flex-col">
        <Head>
          <title>Qotoof Charity</title>
          <meta name="Charity org" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <div className="flex h-screen flex-row">
          <SideBar />
          <SWRConfig
            value={{
              fetcher,
              refreshInterval: 20000,
              shouldRetryOnError: false,
            }}
          >
            <Component {...pageProps} />
          </SWRConfig>
        </div>
      </div>
    </Provider>
  );
}

export default MyApp;
