import { AppProps } from 'next/app';
import Head from 'next/head';
import { Provider } from 'react-redux';
import NavBar from '../components/NavBar';
import '../../styles/globals.css';
import store from '../redux/store';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <div className="flex h-screen flex-row">
        <Head>
          <title>Qotoof Charity</title>
          <meta name="Charity org" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />
        <Component {...pageProps} />
      </div>
    </Provider>
  );
}

export default MyApp;
