import Head from 'next/head'
import Image from 'next/image'
import { useRef,useEffect,useState } from 'react';
import styles from '../../styles/Home.module.css'
import useSWR  from 'swr';

export default function Home() {

 const [response, setResponse] = useState("");

 //Todo: useEffect on new cases addition

  const nameInputRef = useRef(null)

  const fetcher = (url) => fetch(url).then((res) => res.json());
  const { data, error } = useSWR("http://localhost:8000/beneficiaryList", fetcher);

  let output

  if (error) output = "An error has occurred.";
  if (!data) output = "Loading...";
  if (data) output=(<>{data.map(x => <h4>{x.beneficiaryName}</h4> )}</>)

  const submitToBackend = async (e) => {
    e.preventDefault();
    const beneficiaryName = nameInputRef.current.value;
   await fetch("http://localhost:8000/beneficiary", {
     method: "POST",
     headers: {
       "Content-Type": "application/json",
     },
     body: JSON.stringify({beneficiaryName}),
   })
     .then((res) => {
       console.log(res);

       // .json() converts JSON object to JS object
       return res.json();
     })
     .then((data) => setResponse(`${data.beneficiaryName} is added successfully`))
     .catch((err) => console.log(err));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Qotoof Charity</title>
        <meta name="Charity org" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Entering Form</h2>
        <form onSubmit={submitToBackend}>
          <label htmlFor="beneficiary">Beneficiary Name</label>
          <input type={"text"} name={"beneficiary"} ref={nameInputRef} />
          <button type="submit">Submit to backend</button>
        </form>
        <h4>{response}</h4>
        {output}
      </main>
    </div>
  );
}