import Head from 'next/head';
import React, { useRef, useState } from 'react';
import API_ENDPOINT from '../utils/constants';
import Button from './Button';

type Props = {};

function BenForm(props: Props) {
  const [response, setResponse] = useState<JSX.Element | string>('');

  const nameInputRef = useRef(null);

  const submitToBackend = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    const beneficiaryName = nameInputRef.current.value;
    try {
      const res = await fetch(`${API_ENDPOINT}/`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ beneficiaryName }),
      });
      const data = await res.json();
      setResponse(`${data.name} is added successfully`);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div className="bg-cyan-300">
      <Head>
        <title>Qotoof Charity</title>
        <meta name="Charity org" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Entering Form</h2>
        <form onSubmit={submitToBackend}>
          <label htmlFor="beneficiary">Beneficiary Name</label>
          <input
            className="border-2 border-black"
            type="text"
            id="beneficiary"
            ref={nameInputRef}
          />
          <Button
            text="Add Beneficiary"
            type="submit"
            handleClick={submitToBackend}
          />
        </form>
        <h4>{response}</h4>
      </main>
    </div>
  );
}

export default BenForm;
